In [16]:
from IPython.display import display
from IPython.display import HTML
import IPython.core.display as di # Example: di.display_html('<h3>%s:</h3>' % str, raw=True)

# This line will hide code by default when the notebook is exported as HTML
di.display_html('<script>jQuery(function() {if (jQuery("body.notebook_app").length == 0) { jQuery(".input_area").toggle(); jQuery(".prompt").toggle();}});</script>', raw=True)

# This line will add a button to toggle visibility of code blocks, for use with the HTML export version
di.display_html('''<button onclick="jQuery('.input_area').toggle(); jQuery('.prompt').toggle();">Toggle code</button>''', raw=True)

Toggle code

In [17]:
import numpy as np
import pandas as pd
import scipy

In [19]:
# number
x = 5
y = 6
print(x + y)

# string
my_string = "python"
print(my_string)

11
python


In [28]:
# length of a string
print(len(my_string))

# concatenation
print("my " + my_string)

# coercion
print("my " + my_string + " is level " + str(x))

# visit a character: 0-index
print(my_string[3])
print(my_string[-1]) ###负号代表从后往前数的顺序

# string manipulations
print(my_string.upper()) ###"upper" means using upper case.
print(my_string.replace("y", "yyyy"))
print(my_string.find("y")) ###"find" means to find the letter's index(序数).

6
my python
my python is level 10
h
n
PYTHON
pyyyython
1


In [42]:
colors = ["red", "blue", "green"]
print(colors)
print(colors[0])
print(len(colors)) 

# manipulation
# append at the bottom
colors.append("yellow") ###"append" means to add a new one next to the last one. 
print(colors)

# insert at any position
colors.insert(1, "pink")
print(colors)

# remove an element
colors.pop(1)
print(colors)

# search for an element
colors.index("green")

# quiz: what if there's duplicate
colors = ["red", "blue", "blue", "green"]
print(colors.index("blue"))

# quiz: what about other stuff? remove duplicate?
# answer: use numpy which handles this type of stuff

['red', 'blue', 'green']
red
3
['red', 'blue', 'green', 'yellow']
['red', 'pink', 'blue', 'green', 'yellow']
['red', 'blue', 'green', 'yellow']
1


In [24]:
# if/else. simple example
x = 10
if x == 5:
    print("Yes")
else:
    print("No")

No


In [25]:
# if/else. complex example
speed = 82
mood = "bad"

if speed >= 80:
    print 'License and registration please'
    if mood == 'terrible' or speed >= 100:
        print 'You have the right to remain silent.'
    elif mood == 'bad' or speed >= 90:
        print "I'm going to have to write you a ticket."
    else:
        print "Let's try to keep it under 80 ok?"

License and registration please
I'm going to have to write you a ticket.


In [26]:
# for loop
primes = [2, 3, 5, 7]
for prime in primes:
    print(prime)

2
3
5
7


In [27]:
# tuple yizudongxi&can not change &similar to "list"
my_tuple = ("price", 5.7)
print(len(my_tuple))
print(my_tuple[1])

2
5.7


In [32]:
# create a column vector
col_vec = np.array([[1], [2]])
print col_vec
    
# create a row vector
row_vec = np.array([[1, 2]])
print row_vec
    
# create a matrix
my_matrix = np.array([[1, 2, 3], [3, 4, 5]])
print my_matrix
    


[[1]
 [2]]
[[1 2]]
[[1 2 3]
 [3 4 5]]


In [34]:
# inspect dimensions
shape = my_matrix.shape
print "matrix rows", shape[0], "columns", shape[1] ###"shape" is all about the numbers of rows and columns of a matrix.
    
# transpose
my_matrix_t = my_matrix.transpose()
print "transposed matrix"
print my_matrix_t

# matrix calculation 
# addition
a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 2], [3, 4]])
print "a + b"
print a + b

# subtraction
print "a - b"
print a - b

# multiplication (meaningless)
print "a * b"
print a * b



matrix rows 2 columns 3
transposed matrix
[[1 3]
 [2 4]
 [3 5]]
a + b
[[2 4]
 [6 8]]
a - b
[[0 0]
 [0 0]]
a * b
[[ 1  4]
 [ 9 16]]


In [52]:
# matrix product
# print "matrix product"
# print np.dot(A, B) ###https://www.youtube.com/watch?v=sYlOjyPyX3g 要看。

# more interesting stuff:
# on 1d array, which is essentially a list.
my_array = np.array([1, 2, 3, 4])
print(my_array) #[1,2,3,4]
print(len(my_array)) #4
print(my_array.sum()) #10
print(my_array.max()) #4
print(my_array.mean()) #2.5
# my_list = [1,2,3,4]
# print(my_list.sum()) returned Error

# quiz:
my_array = np.array([1, 2, 2, 4, 5])
print(np.unique(my_array)) #[1,2,4,5]

# other stuff:
# subset
print(my_array[-1]) #5
print(my_array[my_array>2]) # the inside my_array>2 will return the index of which number>2; 
                            # the outer my_array will return the numbers of which index you returned last step.
# add/remove element
print(np.append(my_array, 6)) # *
print(np.insert(my_array, 3, -2)) # the first number means the index of the number you want to insert;
                                  # the second number means the number you need to insert. 
print(np.delete(my_array, [1,2])) # the numbers mean index!

[1 2 3 4]
4
10
4
2.5
[1 2 4 5]
5
[4 5]
[1 2 2 4 5 6]
[ 1  2  2 -2  4  5]
[1 4 5]


In [50]:
df = pd.DataFrame(
    data = {
        "customer_id": ["A", "B", "C"],
        "date": ["5/1/2017", "5/8/2017", "5/11/2017"],  
        "spend": [10, 5, 20]
    },
  # index = [1, 2, 3],
    columns = ["customer_id", "date", "spend"]
)
print(df)
# https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.html
# describe table
print(df.shape)

# subset columns
print(df["spend"])
print(df[["customer_id", "spend"]])

# subset rows
print(df.sample(n = 1))
print(df.head(n = 1))

  customer_id       date  spend
0           A   5/1/2017     10
1           B   5/8/2017      5
2           C  5/11/2017     20
(3, 3)
0    10
1     5
2    20
Name: spend, dtype: int64
  customer_id  spend
0           A     10
1           B      5
2           C     20
  customer_id      date  spend
1           B  5/8/2017      5
  customer_id      date  spend
0           A  5/1/2017     10


In [69]:
# select columns
my_data = pd.read_csv('BA501_python_data.csv')
# print(my_data[["user_id","date","spend_usd"]].head(10))
# print(my_data["user_id"].head(10))
# print(np.unique(my_data["country"]))

# select rows
# print(my_data[1:10]) # the numbers are index, the left one is included in the returned list whereas the right one is not. 
# print(my_data[(my_data.user_id == 5006730028073359543) & (my_data.country == "JP")])

# create new columns
my_data['spend_usd_whole'] = my_data['spend_usd']*5
# print(my_data.head(5))

# drop this column
my_data = my_data.drop("spend_usd_whole", axis = 1) #'axis = 1' means it's a column;'axis = 0' means it's a row.
print(my_data.head(10))

  country      date  experiment_id              order_id  spend_usd  \
0      JP  20170402       12624548   5813140433216629693  16.138855   
1      US  20170403       12624549  16333056276711034931   9.990000   
2      JP  20170404       12624548  11227119161741298366  19.887087   
3      US  20170403       12624548  11927299833124210932  19.990000   
4      JP  20170403       12624549  11644727017708872749  88.220093   
5      FR  20170406       12624548   2887851716418524034  10.641677   
6      US  20170406       12624548   8835194413765780524   9.990000   
7      US  20170402       12624549   2761291987218019434  10.090000   
8      US  20170405       12624548   9027895522629963459   9.990000   
9      US  20170405       12624548   2588200289165850850  19.990000   

                user_id      vertical  
0   5006730028073359543  ANDROID_APPS  
1   5938685669571545259  ANDROID_APPS  
2  17623708458399141713  ANDROID_APPS  
3  18042812344456618148  ANDROID_APPS  
4   43251047006995

In [78]:
# select *: see "select columns"

# where: see "select rows"

# Groupby: groupby()
result = my_data.groupby(["country"])["spend_usd"].sum()
# print(result)
result = my_data.groupby(["country"])["spend_usd"].sum().reset_index()
# print(result)
result = result.set_index("country")
# print(result)

# save as a new dataframe, and reset your index
# Order by: sort_values()
my_data = my_data.sort_values(['country','date'],ascending=[False, False])
my_data.head(5)
print(my_data.head(5))
# Join: merge()
# left join
#pd.merge(left_table, right_table,how='left',on='x1')

# Union: concat(), stack()
#pd.concat([left_table, right_table])

      country      date  experiment_id              order_id  spend_usd  \
2673       ZA  20170407       12624548  10408259180986743164   1.088080   
13338      ZA  20170407       12624549  16400872559986890759   8.689793   
13374      ZA  20170407       12624549  12381462873414547336   7.257980   
13492      ZA  20170407       12624549  15719408519960453436   7.257980   
14497      ZA  20170407       12624549    462012274643780937   4.717432   

                    user_id      vertical  
2673    3410001499694617342  ANDROID_APPS  
13338  10774269234984234779  ANDROID_APPS  
13374   7545696287574813995  ANDROID_APPS  
13492  10854157887295607650  ANDROID_APPS  
14497  10665734066659640439  ANDROID_APPS  
